version: 2
updates:
- package-ecosystem: github-actions
  # Workflow files stored in the default location of `.github/workflows`
  directory: "/"
  schedule:
    interval: "weekly"
  target-branch: "main"
  groups:
    production-dependencies:
      dependency-type: production
  cooldown:
    default-days: 10
- package-ecosystem: docker
  directory: "/index"
  schedule:
    interval: "daily"
  target-branch: "main"
- package-ecosystem: "uv"
  directory: "/index"
  schedule:
    interval: "weekly"
  groups:
    uv-deps:
      patterns:
        - "*"
