name : Build Docker Images

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: opendatacube/datacube-index"

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Index
      run: |
        docker build index 
    
    - name: Build Index
      run: |
        docker build statistician
